"""Contains the BoundingBoxDetection class."""

from core.geometry import Rectangle
from functools import cached_property
from pydantic import BaseModel, ConfigDict, computed_field


class BoundingBoxDetection(BaseModel):
    """A BoundingBox generated by a computer vision model.

    Attributes:
        rectangle (Rectangle):
            The rectangle that this BoundingBoxDetection encloses.
        category_scores (list[float]):
            An ordered list of confidence scores for each category. Each entry lines up with
            the an ordered list of category names such that if they are zipped, the resulting
            list will give the name and confidence of each category.
        top_category_id (int):
            The index of the category with the highest confidence.
        confidence (float):
            The highest confidence probability among all the category confidences.
    """

    model_config = ConfigDict(frozen=True)

    rectangle: Rectangle
    category_scores: list[float]

    @computed_field
    @cached_property
    def confidence(self) -> float:
        """The highest confidence probability among all the category confidences.

        Returns:
            The confidence probability associated with the category of highest confidence.
            Typically this is considered what the model 'classifies' this detection as.
        """
        return max(self.category_scores)

    @computed_field
    @cached_property
    def top_category_id(self) -> int:
        """The index of the category with the highest confidence.

        Breaks ties by selecting the first occurance of the id with maximum confidence.

        Returns:
            The index of the category with the highest confidence.
        """
        return self.category_scores.index(self.confidence)
