"""Contains the BoundingBoxWithKeypointsDetection class."""

from core.detections import BoundingBoxDetection, KeypointDetection
from pydantic import BaseModel, ConfigDict


class BoundingBoxWithKeypointsDetection(BaseModel):
    """A bounding box with keypoints generated by a computer vision model.

    Attributes:
        bounding_box_detection (BoundingBoxDetection):
            The detected bounding box.
        keypoint_detections (list[KeypointDetection]):
            An ordered list of the detected keypoints.
    """

    model_config = ConfigDict(frozen=True)

    bounding_box_detection: BoundingBoxDetection
    keypoint_detections: list[KeypointDetection]
