"""Contains the KeypointDetection class."""

from core.geometry import Point
from pydantic import BaseModel, ConfigDict


class KeypointDetection(BaseModel):
    """A keypoint generated by a computer vision model.

    Attributes:
        point (Point):
            The xy point this keypoint detection is located at.
        confidence (float):
            The generating model's certainty that the keypoint is present and accurately localized.
            The exact interpretation of what this score means differs between models.
        classification (str | None):
            The name of the keypoint. Typically the container that holds KeypointDetections will
            resolve the names of the keypoints without storing them, but it remains an option.
            Defaults to None.
    """

    model_config = ConfigDict(frozen=True)

    point: Point
    confidence: float
    classification: str | None = None
