"""Contains the ObjectDetections class."""

from core.detections import BoundingBoxDetection
from pydantic import BaseModel, ConfigDict


class ObjectDetections(BaseModel):
    """A collection of bounding box detections coupled with class names.

    Attributes:
        detections (list[BoundingBoxDetection]):
            The bounding box detections generated by a computer vision model.
        class_names (list[str]):
            An ordered list of the names of the classes. If zipped with any bounding box
            detections category_scores, it will produce a list containing the name of each class
            along with the confidence probability assigned to it by the model.
    """

    model_config = ConfigDict(frozen=True)

    detections: list[BoundingBoxDetection]
    class_names: list[str]
