intraoperative_document_landmarks:
  name: intraop_doc_landmark_detector.pt
  tile_size_proportion: 0.3
preop_postop_document_landmarks:
  name: preop_postop_doc_landmark_detector.pt
  tile_size_proportion: 0.3
numbers:
  name: digits.pt
  tile_size_proportion: 0.3
systolic:
  name: sys_yolov11m_pose_best_no_transfer.pt
  tile_size_proportion: 0.3
diastolic:
  name: dia_yolov11m_pose_best_no_transfer.pt
  tile_size_proportion: 0.3
heart_rate:
  name: hr_yolov11m_pose_best_no_transfer.pt
  tile_size_proportion: 0.3
checkboxes:
  name: yolov11s_checkboxes.pt
  tile_size_proportion: 0.3