name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Sphinx & Dependencies
      run: pip install sphinx sphinx_markdown_builder sphinx_rtd_theme
    - name: Install External Requirements
      run: pip install -r requirements.txt
    - name: Build Documentation
      run: cd "$GITHUB_WORKSPACE/docs" && make html
    - name: list
      run: ls

    - uses: actions/upload-artifact@v4
      with:
        name: Documentation
        path: "$GITHUB_WORKSPACE/docs/build/html/"